# more settings under: https://alacritty.org/config-alacritty.html
general.import = ["/home/arminveres/.config/alacritty/gruvbox-black.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12
builtin_box_drawing = true

[font.glyph_offset]
x = 0
y = 0

[font.normal]
# family = "TamzenForPowerline"
family = "Terminus"

[font.offset]
x = 0
y = 0

[scrolling]
# auto_scroll = false
history = 10000
multiplier = 3

[window]
dynamic_padding = true
opacity = 0.9
option_as_alt = "OnlyLeft"

[window.padding]
x = 3

[mouse]
hide_when_typing = true

[env]
# allows for same font size on monitors with different resolutions
WINIT_X11_SCALE_FACTOR = "1.0"

[terminal.shell]
program = "/usr/bin/env"
args = ["tmux"]

[keyboard]
bindings = [{ key = "Slash", mods = "Control", chars = "\u001f" }]
