# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

git:
  pagers:
    - pager: delta --dark --paging=never
    - pager: delta --dark --paging=never --side-by-side
    - externalDiffCommand: difft --color=always --syntax-highlight=off #--display=inline
  autoStageResolvedConflicts: false
