#!/bin/bash

# This is an install script for Fedora WS GNOME edition, which will use I3 
# (thus x11) and zsh as main components

# add repo for ffmpeg 
sudo dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf -y install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

sudo dnf install -y \
    htop \
    lm_sensors \
    neovim \
    xrandr \
    rofi \
    ranger \
    speedtest-cli \
    xinput \
    zsh \
    i3-gaps \
    alacritty \
    network-manager-applet \
    pasystray \
    ffmpeg \
    ffmpeg-devel \
    gcc \
    g++ \
    clang \
    clang-tools-extra \
    cmake \
    playerctl \
    stow \
    node \
    python3-pip \
    rubygem \
    fd-find \
    flatpak
