font = "IosevkaTerm Nerd Font Mono"
font-size = 17.5
# font = "MesloLGS Nerd Font"
# font = "NotoMono Nerd Font Mono"
# font = "RobotoMono Nerd Font Mono"
# font = "DejaVuSansMono Nerd Font Mono"
# font = "DinaRemasterII"
# font = "TamzenForPowerline"
# font-size = 14

# Cursor
#
# Default cursor is Block
# Other available options are: '_' and '|'
# cursor = '_'

# Perfomance
#
# Set WGPU rendering performance
# High: Adapter that has the highest performance. This is often a discrete GPU.
# Low: Adapter that uses the least possible power. This is often an integrated GPU.
# performance = "High"

# Theme
#
# It makes Rio look for the specified theme in the themes folder
# (macos and linux: ~/.config/rio/themes/dracula.toml)
# (windows: C:\Users\USER\AppData\Local\rio\themes\dracula.toml)
#
# Dracula theme code is available in:
# https://github.com/dracula/rio-terminal
theme = "gruvbox"

# Colors
#
# Colors definition will overwrite any property in theme
# (considering if theme folder does exists and is being used)
# [colors]
# background = "#BBBD64"
# foreground = "#040400"
# cursor = "#242805"
# tabs-active = "#F8A145"
# blue = "#454A12"

# Padding-x
#
# define x axis padding (default is 10)
padding-x = 10

# Option as Alt
#
# This config only works on MacOs.
# Possible choices: 'both', 'left' and 'right'.
# option_as_alt = 'both'

# Window Opacity
#
# window-opacity changes the window transparency state.
# Only works for Windows / X11 / WebAssembly
# window-opacity = 0.9

# Window Width
#
# window-width changes the intial window width.
# Default: 600
# window-width = 1200

# Window Height
#
# window-height changes the inital window height.
# Default: 400
# window-height = 800

# Navigation
#
# "mode" - Define navigation mode: CollapsedTab, BottomTab, TopTab, Breadcrumb.
# "clickable" - Enable click on tabs to switch.
# "use-current-path" - Use same path whenever a new tab is created.
# "color-automation" - Set a specific color for the tab whenever a specific program is running.
# "macos-hide-window-buttons" - (MacOS only) Hide window buttons
#
[navigation]
mode = "Breadcrumb"
clickable = false
use-current-path = true
color-automation = [
  { program = "nvim", color = "#FFFF00" }
]
macos-hide-window-buttons = false

# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g. `/bin/fish`.
# Entries in `shell.args` are passed unmodified as arguments to the shell.
#
# Default:
#   - (macOS) user login shell
#   - (Linux/BSD) user login shell
#   - (Windows) powershell
#
shell = { program = "/bin/zsh", args = ["--login", "--interactive"] }

# Startup directory
#
# Directory the shell is started in. If this is unset the working
# directory of the parent process will be used.
#
# This configuration only has effect if use-fork is disabled
# working_dir = "/Users/raphael/Documents/"

# Editor
#
# You can set your default editor to open configuration file
#
# Default:
#   - (macOS) value of $EDITOR with a fallback to "vim"
#   - (Linux/BSD) value of $EDITOR with a fallback to "vi"
#   - (Windows) value of $EDITOR with a fallback to "vi"
#
# The example below sets VS Code as default editor
# editor = "code"

# Environment variables
#
# The example below sets fish as the default SHELL using env vars
# please do not copy this if you do not need
# env-vars = ['SHELL=/opt/homebrew/bin/fish']

# Disable render when unfocused
#
# This property disable renderer processes while Rio is unfocused.
# disable-renderer-when-unfocused = true

# Use fork
#
# Defaults for POSIX-based systems (Windows is not configurable):
# MacOS: spawn processes
# Linux/BSD: fork processes
#
use-fork = true


# Bindings
#
# Create custom Key bindings for Rio terminal
# More information in: raphamorim.io/rio/docs/custom-key-bindings
[bindings]
keys = [
  { key = "q", with = "super", action = "Quit" },
  # Bytes[27, 91, 53, 126] is equivalent to "\x1b[5~"
  { key = "home", with = "super | shift", bytes = [27, 91, 53, 126] }
]

[developer]
# Log level
#
# This property enables log level filter. Default is "OFF".
log-level = "WARN"
