[colors]
background       = '#000000'
foreground       = '#D5C4A1'
cursor           = '#D5C4A1'
# tabs             = '#494c62'
# tabs-active      = '#6a6e8e'
black            = '#000000'
blue             = '#83a598'
cyan             = '#8EC07C'
green            = '#B8BB26'
magenta          = '#D3869B'
red              = '#FB4934'
white            = '#D5C4A1'
yellow           = '#FABD2F'
# dim-black        = '#393C4b'
# dim-blue         = '#AE7BF8'
# dim-cyan         = '#69C3dE'
# dim-foreground   = '#dfdfd9'
# dim-green        = '#06572F'
# dim-magenta      = '#FF60BB'
# dim-red          = '#FF3C3C'
# dim-white        = '#EFEFE1'
# dim-yellow       = '#E6A003'
# light-black      = '#6272A4'
# light-blue       = '#D6ACFF'
# light-cyan       = '#A4FFFF'
# light-foreground = '#f8f8f1'
# light-green      = '#69FF94'
# light-magenta    = '#FF92DF'
# light-red        = '#FF6E6E'
# light-white      = '#FFFFFF'
# light-yellow     = '#FFFFA5'
